#index:
#    path:         /index.php
#    controller:   App\Controller\FrameworkBundle\TemplateController
#    defaults:
#        template: login.html
#    methods: GET

    #Account endpoints
login:
    path: /login
    controller: App\Controller\AccountController::login
    methods: POST

getAuthenticatedURL:
    path: /getAuthenticatedURL
    controller: App\Controller\AccountController::getAuthenticatedURL
    methods: POST

    #Templates

loginPage:
    path:         /login.html
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: login.html
    methods: GET

portalTemplate:
    path:         /{portalId}/overview.html
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: portal.html
    methods: GET
