#index:
#    path:         /index.php
#    controller:   App\Controller\FrameworkBundle\TemplateController
#    defaults:
#        template: login.html
#    methods: GET

    #Portal endpoints
login:
    path: /login
    controller: App\Controller\PortalController::login
    methods: POST

getPortalDetails:
    path: /getPortalDetails
    controller: App\Controller\PortalController::getPortalDetails
    methods: POST

    #Product endpoints

updateProducts:
    path: /products
    controller: App\Controller\ProductsController::updateProducts
    methods: POST

    #Templates

loginPage:
    path:         /login.html
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: login.html
    methods: GET

portalTemplate:
    path:         /overview.html
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: portal.html
    methods: GET
